<template>
  <v-container>
    <h2 class="display-2 pb-4">Proyects</h2>

    <v-layout row wrap>
      <v-flex xs12 md6 pa-2 v-for="(item, index) in proyect" :key="index">
        <v-card hover>

          <v-card-title primary-title style="position: relative;">
            <v-layout row wrap>
              <v-flex xs12 class="py-2">
                <h3 class="headline"><b>{{item.name}}</b> ({{item.date}})</h3>
              </v-flex>

              <v-flex xs12>
                <p class="title">
                  <b>Technologies</b>: {{item.technologies}}
                </p>
              </v-flex>

              <span class="py-2" v-if="item.link">
                <v-btn :href="item.link" target="_blank" color="secondary" round bottom right absolute style="z-index: 2;">
                  <v-icon left>link</v-icon> Link
                </v-btn>
              </span>
            </v-layout>
          </v-card-title>

          <v-divider></v-divider>

          <v-img v-if="!item.images" :src="item.image" height="300"></v-img>

          <swiper :options="swiperOption2" ref="mySwiper3" v-if="item.images">
            <swiper-slide v-for="(item, i) in item.images" :key="i">
              <v-layout rwo justify-center>
                <img class="autoSizeImage" :src="item"/>
              </v-layout>
            </swiper-slide>
            <div class="swiper-pagination" slot="pagination"></div>
          </swiper>

          <v-divider></v-divider>

          <v-card-title primary-title class="justifyText">
            <v-layout column>
              <div class="title pb-1"><b>Description</b></div>
              <div class="subheadline" v-html="item.description"></div>
            </v-layout>
          </v-card-title>
        </v-card>
      </v-flex>
    </v-layout>
  </v-container>
</template>

<script>
export default {

  computed: {
    breakpoint: function () { return this.$vuetify.breakpoint }
  },

  data() {
    return {
      show: false,
      proyect: [
        {
          name: 'Datathon Cajamar',
          date: '2017',
          link: 'https://datavizuji.firebaseapp.com/',
          image: 'image/projects/datathon.png',
          description: '<p>The objective of the proposed challenge in the Datathon was to create an application to interactively show the data generated by the credit card purchases of Cajamar\'s customers.</p><p>The original dataset contained the zip code of the customer and the trade, the trade sector, the date of the transaction, the time slot, the amount and the number of transactions carried out. To obtain a better score in the challenge, it was necessary to add external sources of data, therefore we added the climatology and the population by postal code of the province of Valencia.</p>',
          technologies: 'Tableau, Knime and Firebase.',
        },
        {
          name: 'Hackathon Castellón',
          date: '2016',
          link: 'http://www.hackathoncastellon.com/',
          image: 'image/projects/hackathon1.png',
          images: [
            'image/projects/hackathon1.png',
            'image/projects/hackathon2.png',
            'image/projects/hackathon3.png',
            'image/projects/hackathon4.png',
            'image/projects/hackathon5.png',
          ],
          description: '<p>In the Hackathon of Castellón we had 48 hours to solve one of the 4 challenges proposed. We participated in a group of 5 colleagues from the university and the challenge we chose was to <b>create an application</b> that helps the user to <b>know a city interactively</b>. For this, we developed a <b>cross-platform application</b> with new technologies that we had not used and thus leave our comfort zone.</p>',
          technologies: 'Ionic 2, Angular 2, Typescript, google maps and Firebase.',
        },
      ],

      // proyect: [
      //   {
      //     name: 'Hackathon Castellón',
      //     date: '2016',
      //     link: 'http://www.hackathoncastellon.com/',
      //     image: 'image/projects/hackathon1.png',
      //     images: [
      //       'image/projects/hackathon1.png',
      //       'image/projects/hackathon2.png',
      //       'image/projects/hackathon3.png',
      //       'image/projects/hackathon4.png',
      //       'image/projects/hackathon5.png',
      //     ],
      //     description: '<p>En el Hackathon de Castellón dispusimos de 48 horas para resolver uno de los 4 retos propuestos. Participamos un grupo de 5 compañeros de la carrera y el reto que elegimos consistió en <b>crear una aplicación</b> que ayudase al usuario a <b>conocer una ciudad de forma interactiva</b>. Para ello, desarrollamos una <b>aplicación multiplataforma</b> con nuevas tecnologías que no habíamos utilizado y de esta forma salir de nuestra zona de confort.</p>',
      //     technologies: '<p><b>Ionic 2</b>, <b>Angular 2</b>, Typescript, google maps and <b>Firebase</b>.</p>',
      //   },
      //   {
      //     name: 'Datathon Cajamar',
      //     date: '2017',
      //     link: 'https://datavizuji.firebaseapp.com/',
      //     image: 'image/projects/datathon.png',
      //     description: '<p>El objetivo del reto propuesto en el Datathon, era crear una aplicación para mostrar de forma interactiva los datos generados por las compras con tarjeta de crédito de los clientes de Cajamar desde la provincia de Valencia a comercios de la ciudad de Valencia.</p><p>El dataset original contenía el código postal del cliente y del comercio, el sector del comercio, la fecha de la transacción, la franja horaria, el importe y el número de operaciones realizadas. Para obtener mejor puntuación en el reto, era necesario añadir fuentes externas de datos, por lo tanto añadimos la climatología y la población por código postal de la provincia de Valencia.</p>',
      //     technologies: '<p><b>Tableau</b>, <b>Knime</b> and <b>Firebase</b>.</p>',
      //   },
      // ],

      swiperOption2: {
        autoplay: {
          delay: 5000,
          disableOnInteraction: false
        },
        pagination: {
          el: '.swiper-pagination',
          clickable: true
        },
      },
    }
  },

}
</script>

<style scoped>
  .autoSizeImage {
    height: 330px;
    width: auto;
  }

  .mediaPadding {
    padding: 0px 0px;
  }

  @media (max-width: 599px) {
    .mediaPadding {
      padding: 32px 0px;
    }
  }
</style>
